name: Upload Repo to S3

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Zip
        run: sudo apt-get install -y zip

      - name: Create ZIP Archive
        run: zip -r repo.zip . -x "*/.git/*"  # Excludes .git folder

      - name: Upload ZIP to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp repo.zip s3://$S3_BUCKET_NAME/latest-repo.zip --region $AWS_REGION
